### environment_variables.conf
### Commentary:
## Desktop-wide environment variables.
### Configuration:

$cursorSize = 20
$cursorTheme = Bibata-Modern-Classic

env = XCURSOR_SIZE,$cursorSize
env = XCURSOR_THEME,$cursorTheme
env = HYPRCURSOR_SIZE,$cursorSize
env = HYPRCURSOR_THEME,$cursorTheme
