### my_programs.conf
### Commentary:
## Key programs.
### Configuration:

## See https://wiki.hypr.land/Configuring/Keywords/

## Set programs that you use
$terminal = foot
$fileManager = thunar
$menu = fuzzel
